config/routes.rb
Wellversed::Application.routes.draw do
  resources :users do
    member do
      get :studying
    end
  end
  resources :sessions, only: [:new, :create, :destroy]
  resources :studies do
    get "practise"
  end

  root to: 'static_pages#home'

  match '/signup',  to: 'users#new'
  match '/signin',  to: 'sessions#new'
  match '/signout', to: 'sessions#destroy'
  
  match '/help',    to: 'static_pages#help'
  match '/about',   to: 'static_pages#about'
  match '/contact', to: 'static_pages#contact'

  match '/studies/practise', to: 'studies#practise'

  resources :pieces
  resources :users
  resources :authors

end

app/models/author.rb
# == Schema Information
#
# Table name: authors
#
#  id         :integer          not null, primary key
#  name       :string(255)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Author < ActiveRecord::Base
  attr_accessible :name
  has_many :pieces
#  accepts_nested_attributes_for :pieces

  validates :name, presence: true, uniqueness: { case_sensitive: false }

#  def author
#  	@author = Author.new
#  end
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
	def index
		@authors = Author.all

		respond_to do |format|
			format.html # index.html.erb
			format.json { render json: @author }
		end
	end

	def show
    	@author = Author.find(params[:id])

    	respond_to do |format|
    		format.html # show.html.erb
    		format.json { render json: @piece }
   		end
	end

  # GET /authors/new
  # GET /authors/new.json
	def new
		@author = Author.new

		respond_to do |format|
			format.html # new.html.erb
			format.json { render json: @author }
		end
	end

	def create
		@author = Author.new(params[:author])
    
		respond_to do |format|
			if @author.save
        		format.html { redirect_to @author, notice: 'Author was successfully created.' }
        		format.json { render json: @author, status: :created, location: @author }
    		else
    			format.html { render action: "new" }
    			format.json { render json: @author.errors, status: :unprocessable_entity }
      		end
    	end
  	end

end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/views/authors/_form.html.erb
<%= form_for @author do |f| %>
  <% if @author.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@author.errors.count, "error") %> prohibited this author from being saved:</h2>

      <ul>
      <% @author.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= fields_for @author do |ff| %>
      <%= ff.label :name %><br />
      <%= ff.text_field :name %>
    <% end %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/authors/index.html.erb
<h1>Backups</h1>

<table class="pieces">
  <tr>
    <th>Author</th>
    <th></th>
    <th></th>
  </tr>

<% @authors.each do |author| %>
  <tr>
    <td><%= link_to author.name, author %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Author', new_author_path %>

app/views/authors/new.html.erb
<h1>New backup</h1>

<%= render 'form' %>

<%= link_to 'Back', authors_path %>

app/views/authors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Author:</b>
  <%= @author.name %>
</p>
<ul>
<% @author.pieces.each do |piece| %>
    <li><%= link_to piece.title, piece %></td>
<% end %>
</ul>