config/routes.rb
Wellversed::Application.routes.draw do
  resources :users do
    member do
      get :studying
    end
  end
  resources :sessions, only: [:new, :create, :destroy]
  resources :studies do
    get "practise"
  end

  root to: 'static_pages#home'

  match '/signup',  to: 'users#new'
  match '/signin',  to: 'sessions#new'
  match '/signout', to: 'sessions#destroy'
  
  match '/help',    to: 'static_pages#help'
  match '/about',   to: 'static_pages#about'
  match '/contact', to: 'static_pages#contact'

  match '/studies/practise', to: 'studies#practise'

  resources :pieces
  resources :users
  resources :authors

end

app/models/piece.rb
# == Schema Information
#
# Table name: pieces
#
#  id         :integer          not null, primary key
#  author_id  :integer
#  title      :string(255)
#  filename   :string(255)
#  content    :string(255)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Piece < ActiveRecord::Base
  attr_accessible :author_id, :filename, :title, :content
  belongs_to :author
  accepts_nested_attributes_for :author
  attr_accessible :author, :author_attributes

  validates :author_id, presence: true

  def author_name
  	if !author.nil?
  		author.name
  	else
  		"Unknown"
  	end
  end

end

app/controllers/pieces_controller.rb
class PiecesController < ApplicationController
  # GET /pieces
  # GET /pieces.json
  def index
    @pieces = Piece.paginate(page: params[:page], :per_page => 20)
#   @pieces = Piece.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @pieces }
    end
  end

  # GET /pieces/1
  # GET /pieces/1.json
  def show
    @piece = Piece.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @piece }
    end
  end

  # GET /pieces/new
  # GET /pieces/new.json
  def new
    @piece = Piece.new
    @piece.build_author

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @piece }
    end
  end

  # GET /pieces/1/edit
  def edit
    @piece = Piece.find(params[:id])
  end

  # POST /pieces
  # POST /pieces.json
  def create
    @piece = Piece.new(params[:piece])

    # if author exists
    if !Author.find_by_name(params[:author][:name])
      @author = Author.new(params[:author])
      @author.save
    end
    @piece.author_id = Author.find_by_name(params[:author][:name])
    
    respond_to do |format|
      if @piece.save
        format.html { redirect_to @piece, notice: 'Piece was successfully created.' }
        format.json { render json: @piece, status: :created, location: @piece }
      else
        format.html { render action: "new" }
        format.json { render json: @piece.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /pieces/1
  # PUT /pieces/1.json
  def update
    @piece = Piece.find(params[:id])

    @piece.author_id = Author.find_by_name(params[:author][:name])

    ## Added
    if !Author.find_by_name(params[:author][:name])
      @author = Author.new(params[:author])
      @author.save
    end
    @author_id = Author.find_by_name(params[:author][:name])
    @piece.author_id = @author_id

    respond_to do |format|
      if @piece.update_attributes(params[:piece])
        format.html { redirect_to @piece, notice: 'Piece was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @piece.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pieces/1
  # DELETE /pieces/1.json
  def destroy
    @piece = Piece.find(params[:id])
    @piece.destroy

    respond_to do |format|
      format.html { redirect_to pieces_url }
      format.json { head :no_content }
    end
  end

#  def studying
#    @title = "Studying"
#    @user = User.find(params[:id])
#    @pieces = @user.studies.paginate(page: params[:page])
#    render 'show_studies'
#  end

end

app/helpers/pieces_helper.rb
module PiecesHelper
end

app/views/pieces/_form.html.erb
<%= form_for(@piece) do |f| %>
  <% if @piece.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@piece.errors.count, "error") %> prohibited this piece from being saved:</h2>

      <ul>
      <% @piece.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= fields_for @piece.author do |ff| %>
      <%= ff.label :name, "Author" %><br />
      <%= ff.text_field :name %>
    <% end %>
  </div>
  <div class="field">
    <%= f.label :filename %><br />
    <%= f.text_field :filename %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/pieces/_piece.html.erb
<tr>
    <td><%= link_to piece.title, piece %></td>
	<td><%= link_to piece.author_name, author_path(piece.author_id) %></td>
  	<% if signed_in? %>
  		<% if current_user.studies.find_by_piece_id(piece) %>
  	 		<td><%= link_to 'Study', study_path(current_user.studies.find_by_piece_id(piece)) %></td>
  	 	<% end %>
  	 	<% if current_user.admin? %>
    		<td><%= link_to 'Edit', edit_piece_path(piece) %></td>
    		<td><%= link_to 'Delete', piece, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    	<% end %>
  	<% end %>
</tr>

app/views/pieces/_study_form.html.erb
  <% unless current_user?(@user) %>
  <div id="study_form">
  <% if current_user.studying?(@piece) %>
    <%= render 'abandon' %>
  <% else %>
    <%= render 'study' %>
  <% end %>
  </div>
  <% end %>

app/views/pieces/edit.html.erb
<h1>Editing piece</h1>

<%= render 'form' %>

<%= link_to 'Show', @piece %> |
<%= link_to 'Back', pieces_path %>

app/views/pieces/index.html.erb
<h1>Sets</h1>

<%= will_paginate %>

<table class="pieces">
  <tr>
    <th>Title</th>
    <th>Author</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @pieces.order(:title).each do |piece| %>
  <tr>
    <%= render piece %>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Piece', new_piece_path %>

app/views/pieces/new.html.erb
<h1>New piece</h1>

<%= render 'form' %>

<%= link_to 'Back', pieces_path %>

app/views/pieces/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @piece.title %>
</p>

<p>
  <b>Author:</b>
  <%= @piece.author_name %>
</p>
<%= render 'studies/study_form' if signed_in? %>
<p>
<pre>
<%= @piece.content %>
</pre>
  <%#= render :file => 'data/' + @piece.filename %>
</p>


<%= link_to 'Edit', edit_piece_path(@piece) %> |
<%= link_to 'Back', pieces_path %>